package httpapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"

	"github.com/sharepact/us/internal/generator"
)

// "How Well Do You Know Me": per question one partner is the subject (answers
// honestly) and the other guesses. Subject alternates by question index using
// a stable ordering of the two user ids, so both devices agree on roles.
//
// Each pack has a per-couple "round" (see packRoundStore): a generation number
// + the current set of questions + a seenBy list. Answers live in quiz_answers
// under the composite quiz_id `hwdykm:<packID>:g<gen>` so old rounds stay in
// the DB (searchable, but ignored). When both partners have opened results and
// both have answered every question, the round rotates: gen++, a fresh batch
// of questions is generated by Claude (falling back to the seed catalog), and
// the pack becomes playable again with brand-new material.

func hwdykmAnswerKey(packID string, gen int) string {
	return fmt.Sprintf("hwdykm:%s:g%d", packID, gen)
}
func hwdykmRoundGameType(packID string) string { return "hwdykm_pack:" + packID }

type hwdykmRoundContent struct {
	Questions []hwdykmQuestion `json:"questions"`
}

type hwdykmPackSummary struct {
	ID            string `json:"id"`
	Title         string `json:"title"`
	Icon          string `json:"icon"`
	ColorKey      string `json:"colorKey"`
	Tag           string `json:"tag"`
	QuestionCount int    `json:"questionCount"`
	MyDone        bool   `json:"myDone"`
	PartnerDone   bool   `json:"partnerDone"`
	BothDone      bool   `json:"bothDone"`
}

type hwdykmQuestionView struct {
	ID           string         `json:"id"`
	Prompt       string         `json:"prompt"`
	Options      []hwdykmOption `json:"options"`
	SubjectIsMe  bool           `json:"subjectIsMe"` // true → I answer honestly; false → I guess my partner
	MyAnswer     *string        `json:"myAnswer"`
	HonestAnswer *string        `json:"honestAnswer"`
	Guess        *string        `json:"guess"`
	Matched      bool           `json:"matched"`
}

type hwdykmPackDetail struct {
	ID        string               `json:"id"`
	Title     string               `json:"title"`
	Icon      string               `json:"icon"`
	ColorKey  string               `json:"colorKey"`
	Tag       string               `json:"tag"`
	MyDone    bool                 `json:"myDone"`
	BothDone  bool                 `json:"bothDone"`
	Score     int                  `json:"score"`
	Questions []hwdykmQuestionView `json:"questions"`
}

// orderedIDs returns the two user ids in a stable order (subject A, subject B).
func orderedIDs(a, b string) (string, string) {
	if b < a {
		return b, a
	}
	return a, b
}

// ---- helpers -----------------------------------------------------------------

// hwdykmRoundQuestions returns the couple's questions for the current round of
// a pack, creating the round on first access. Falls back to the seed catalog
// when either the round hasn't been rotated yet or the persisted content looks
// corrupt.
func (d Deps) hwdykmRoundQuestions(ctx context.Context, coupleID string, seed hwdykmPack, lang string) (int, []hwdykmQuestion, packRoundState, *packRoundStore, error) {
	rs := d.packRound(coupleID, hwdykmRoundGameType(seed.ID))
	if err := rs.load(ctx); err != nil {
		return 0, nil, packRoundState{}, nil, err
	}
	st := rs.current()
	if st.Generation == 0 {
		content := hwdykmRoundContent{Questions: seed.Questions}
		raw, _ := json.Marshal(content)
		newSt, err := rs.initialize(ctx, "", raw)
		if err != nil {
			return 0, nil, packRoundState{}, nil, err
		}
		return newSt.Generation, seed.Questions, newSt, rs, nil
	}
	var content hwdykmRoundContent
	_ = json.Unmarshal(st.Content, &content)
	if len(content.Questions) < len(seed.Questions) {
		content.Questions = seed.Questions
	}
	return st.Generation, content.Questions, st, rs, nil
}

func (d Deps) generateFreshHwdykmQuestions(ctx context.Context, seed hwdykmPack, lang string, nextGen int) []hwdykmQuestion {
	gen := generator.New(d.Config.AnthropicAPIKey, d.Config.AnthropicModel)
	avoid := make([]string, 0, len(seed.Questions))
	fallback := make([]generator.HwdykmQuestion, 0, len(seed.Questions))
	for _, q := range seed.Questions {
		avoid = append(avoid, q.Prompt)
		opts := make([]string, 0, len(q.Options))
		for _, o := range q.Options {
			opts = append(opts, o.Label)
		}
		fallback = append(fallback, generator.HwdykmQuestion{Prompt: q.Prompt, Options: opts})
	}
	description := ""
	if seed.Tag != "" {
		description = "Tone: " + seed.Tag + "."
	}
	fresh := gen.HwdykmQuestions(ctx, seed.Title, description, len(seed.Questions), avoid, lang, fallback)
	out := make([]hwdykmQuestion, 0, len(fresh))
	for i, q := range fresh {
		out = append(out, hwdykmQuestion{
			ID:      fmt.Sprintf("%s_g%d_q%d", seed.ID, nextGen, i+1),
			Prompt:  q.Prompt,
			Options: hopts(q.Options...),
		})
	}
	return out
}

// ---- handlers ---------------------------------------------------------------

// GET /v1/games/hwdykm/packs
func (d Deps) handleListHwdykmPacks(w http.ResponseWriter, r *http.Request) {
	userID, ok := d.authedUser(w, r)
	if !ok {
		return
	}
	c, ok := d.gameCouple(w, r, userID)
	if !ok {
		return
	}
	partner, _ := d.Store.GetPartner(r.Context(), c.ID, userID)

	keys, err := d.Store.GetQuizAnswerKeys(r.Context(), c.ID)
	if err != nil {
		d.serverError(w, "hwdykm: keys", err)
		return
	}
	counts := make(map[string]map[string]int)
	for _, k := range keys {
		if counts[k.QuizID] == nil {
			counts[k.QuizID] = make(map[string]int)
		}
		counts[k.QuizID][k.UserID]++
	}

	packs := hwdykmPacksFor(langParam(r))
	out := make([]hwdykmPackSummary, 0, len(packs))
	for _, p := range packs {
		gen, questions, _, _, rerr := d.hwdykmRoundQuestions(r.Context(), c.ID, p, langParam(r))
		if rerr != nil {
			d.serverError(w, "hwdykm: round", rerr)
			return
		}
		total := len(questions)
		key := hwdykmAnswerKey(p.ID, gen)
		myDone := counts[key][userID] >= total && total > 0
		partnerDone := partner.ID != "" && counts[key][partner.ID] >= total && total > 0
		out = append(out, hwdykmPackSummary{
			ID: p.ID, Title: p.Title, Icon: p.Icon, ColorKey: p.ColorKey, Tag: p.Tag,
			QuestionCount: total, MyDone: myDone, PartnerDone: partnerDone,
			BothDone: myDone && partnerDone,
		})
	}
	writeJSON(w, http.StatusOK, map[string]any{"packs": out})
}

// GET /v1/games/hwdykm/packs/{id}
func (d Deps) handleGetHwdykmPack(w http.ResponseWriter, r *http.Request) {
	userID, ok := d.authedUser(w, r)
	if !ok {
		return
	}
	c, ok := d.gameCouple(w, r, userID)
	if !ok {
		return
	}
	pack, found := findHwdykmPackIn(hwdykmPacksFor(langParam(r)), chi.URLParam(r, "id"))
	if !found {
		writeError(w, http.StatusNotFound, "unknown_pack", "unknown pack")
		return
	}
	partner, _ := d.Store.GetPartner(r.Context(), c.ID, userID)
	aID, bID := orderedIDs(userID, partner.ID)

	gen, questions, _, _, err := d.hwdykmRoundQuestions(r.Context(), c.ID, pack, langParam(r))
	if err != nil {
		d.serverError(w, "hwdykm: round", err)
		return
	}
	quizID := hwdykmAnswerKey(pack.ID, gen)

	answers, err := d.Store.GetQuizAnswers(r.Context(), c.ID, quizID)
	if err != nil {
		d.serverError(w, "hwdykm: answers", err)
		return
	}
	byUser := make(map[string]map[string]string)
	for _, a := range answers {
		if byUser[a.UserID] == nil {
			byUser[a.UserID] = make(map[string]string)
		}
		byUser[a.UserID][a.QuestionID] = a.Answer
	}

	myDone, partnerDone := true, true
	for _, q := range questions {
		if byUser[userID][q.ID] == "" {
			myDone = false
		}
		if partner.ID == "" || byUser[partner.ID][q.ID] == "" {
			partnerDone = false
		}
	}
	bothDone := myDone && partnerDone

	views := make([]hwdykmQuestionView, 0, len(questions))
	matches := 0
	for i, q := range questions {
		subject := aID
		if i%2 == 1 {
			subject = bID
		}
		guesser := aID
		if subject == aID {
			guesser = bID
		}
		v := hwdykmQuestionView{ID: q.ID, Prompt: q.Prompt, Options: q.Options, SubjectIsMe: subject == userID}
		if mine, ok := byUser[userID][q.ID]; ok && mine != "" {
			v.MyAnswer = &mine
		}
		if bothDone {
			honest := byUser[subject][q.ID]
			guess := byUser[guesser][q.ID]
			v.HonestAnswer = &honest
			v.Guess = &guess
			v.Matched = honest != "" && honest == guess
			if v.Matched {
				matches++
			}
		}
		views = append(views, v)
	}
	score := 0
	if bothDone && len(questions) > 0 {
		score = matches * 100 / len(questions)
	}

	writeJSON(w, http.StatusOK, hwdykmPackDetail{
		ID: pack.ID, Title: pack.Title, Icon: pack.Icon, ColorKey: pack.ColorKey, Tag: pack.Tag,
		MyDone: myDone, BothDone: bothDone, Score: score, Questions: views,
	})
}

// POST /v1/games/hwdykm/packs/{id}/answer  { questionId, answer }
func (d Deps) handleAnswerHwdykmPack(w http.ResponseWriter, r *http.Request) {
	userID, ok := d.authedUser(w, r)
	if !ok {
		return
	}
	c, ok := d.gameCouple(w, r, userID)
	if !ok {
		return
	}
	pack, found := findHwdykmPack(chi.URLParam(r, "id"))
	if !found {
		writeError(w, http.StatusNotFound, "unknown_pack", "unknown pack")
		return
	}
	var req struct {
		QuestionID string `json:"questionId"`
		Answer     string `json:"answer"`
	}
	if !decodeJSON(w, r, &req) {
		return
	}
	gen, questions, _, _, err := d.hwdykmRoundQuestions(r.Context(), c.ID, pack, langParam(r))
	if err != nil {
		d.serverError(w, "hwdykm: round", err)
		return
	}
	var question *hwdykmQuestion
	for i := range questions {
		if questions[i].ID == req.QuestionID {
			question = &questions[i]
			break
		}
	}
	if question == nil {
		writeError(w, http.StatusBadRequest, "unknown_question", "unknown question")
		return
	}
	answer := strings.TrimSpace(req.Answer)
	validOption := false
	for _, o := range question.Options {
		if o.ID == answer {
			validOption = true
			break
		}
	}
	if !validOption {
		writeError(w, http.StatusBadRequest, "unknown_option", "unknown option")
		return
	}
	quizID := hwdykmAnswerKey(pack.ID, gen)
	if err := d.Store.UpsertQuizAnswer(r.Context(), c.ID, quizID, req.QuestionID, userID, answer); err != nil {
		d.serverError(w, "hwdykm: save", err)
		return
	}
	d.notifyTurnOrResults(r.Context(), c.ID, userID, quizID,
		"How Well Do You Know Me", len(questions),
		"You've both finished "+pack.Title+" — see your score 💛",
		map[string]string{"type": "hwdykm", "packId": pack.ID})
	w.WriteHeader(http.StatusNoContent)
}

// POST /v1/games/hwdykm/packs/{id}/seen
//
// Client calls this when the reveal screen opens. Once both partners have
// seen results for the current round (and both have answered every question),
// the round is retired and the next fetch produces a fresh batch of questions.
func (d Deps) handleSeenHwdykmPack(w http.ResponseWriter, r *http.Request) {
	userID, ok := d.authedUser(w, r)
	if !ok {
		return
	}
	c, ok := d.gameCouple(w, r, userID)
	if !ok {
		return
	}
	pack, found := findHwdykmPack(chi.URLParam(r, "id"))
	if !found {
		writeError(w, http.StatusNotFound, "unknown_pack", "unknown pack")
		return
	}
	partner, _ := d.Store.GetPartner(r.Context(), c.ID, userID)

	gen, questions, st, rs, err := d.hwdykmRoundQuestions(r.Context(), c.ID, pack, langParam(r))
	if err != nil {
		d.serverError(w, "hwdykm: round", err)
		return
	}
	quizID := hwdykmAnswerKey(pack.ID, gen)
	answers, err := d.Store.GetQuizAnswers(r.Context(), c.ID, quizID)
	if err != nil {
		d.serverError(w, "hwdykm: answers", err)
		return
	}
	answered := make(map[string]map[string]bool)
	for _, a := range answers {
		if answered[a.UserID] == nil {
			answered[a.UserID] = make(map[string]bool)
		}
		answered[a.UserID][a.QuestionID] = true
	}
	bothDone := partner.ID != ""
	for _, q := range questions {
		if !answered[userID][q.ID] || (partner.ID != "" && !answered[partner.ID][q.ID]) {
			bothDone = false
			break
		}
	}
	if !bothDone {
		if !contains(st.SeenBy, userID) {
			st.SeenBy = append(st.SeenBy, userID)
			_ = rs.save(r.Context(), st)
		}
		w.WriteHeader(http.StatusNoContent)
		return
	}

	_, bothSeen, err := rs.markSeen(r.Context(), userID, partner.ID)
	if err != nil {
		d.serverError(w, "hwdykm: seen", err)
		return
	}
	if bothSeen {
		fresh := d.generateFreshHwdykmQuestions(r.Context(), pack, langParam(r), gen+1)
		raw, _ := json.Marshal(hwdykmRoundContent{Questions: fresh})
		if _, err := rs.bumpGeneration(r.Context(), raw); err != nil {
			d.serverError(w, "hwdykm: bump", err)
			return
		}
	}
	w.WriteHeader(http.StatusNoContent)
}
