-- +goose Up
-- Translated game content (quiz/hwdykm/debate catalogs), generated by
-- cmd/translate against the static English catalogs in internal/http. Rows
-- are content-addressed rather than FK'd to anything, mirroring how
-- quiz_answers already references catalog ids without a foreign key — the
-- catalogs themselves live in code, not the database.
--
-- field is "title" | "prompt" | "option:<optionID>" for the individual pieces
-- of text a catalog item carries. The closed set of Tag values (CUTE/FUN/
-- DEEP/18+/WEDDING) is intentionally NOT stored here — those are translated
-- once as ordinary UI strings (see internal/i18n) and looked up by every
-- catalog item that carries that tag, rather than duplicated per item.
CREATE TABLE content_translations (
    content_type text NOT NULL, -- "quiz_category" | "quiz" | "quiz_question" | "hwdykm_pack" | "hwdykm_question" | "debate_pack" | "debate_motion"
    content_id   text NOT NULL,
    field        text NOT NULL,
    lang         text NOT NULL,
    value        text NOT NULL,
    updated_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (content_type, content_id, field, lang)
);

-- +goose Down
DROP TABLE IF EXISTS content_translations;
